queue: 
  name: Hosted Linux Preview
  
steps:
- task: dotNetCoreCLI@1
  inputs:
    command: restore
    projects: "WhackAMole.MoleCloud/**/*.csproj"
  displayName: dotnet restore

- task: dotNetCoreCLI@1
  inputs:
    command: build
    projects: "WhackAMole.MoleCloud/**/*.csproj"
    arguments: --configuration release
  displayName: dotnet build

# - task: dotNetCoreCLI@1
#   inputs:
#     command: test 
#     projects: "**/*Tests/*.csproj"
#     arguments: --configuration release
#   displayName: dotnet build

- task: dotNetCoreCLI@1
  inputs:
    command: publish
    arguments: WhackAMole.MoleCloud/WhackAMole.MoleCloud.csproj --configuration release --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: true
  displayName: dotnet publish

- task: publishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: drop
    ArtifactType: Container
  displayName: Publish the artifacts