name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches: 
    include:
      - master
      - feature/terraform
  paths:
    include:
      - src/WhackAMole.MoleCloud
      - src/WhackAMole.KubeServices
      - src/Dockerfile.MoleCloud
      - charts/mole-cloud
      - azure-pipelines.mole-cloud.yml

variables:
  image_name: whack-a-mole/mole-cloud:$(Build.BuildNumber)
  report_url: https://demo-whack-a-mole-dev-func.azurewebsites.net/api/ReportBuildState

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    curl -d "{\"State\": 1, \"Message\": \"Initializing Azure CLI Connection\", \"ServiceName\": \"mtcden\"}" -X POST $(report_url)

- task: AzureCLI@1
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: 'MTC Denver Sandbox (b0e04a4a-a321-4b66-b8fd-13715262ba3c)'
    scriptLocation: inlineScript
    inlineScript: |

      # User ACR to build and tag our container
      curl -d "{\"State\": 1, \"Message\": \"Executing Azure Container Registry Build...\", \"ServiceName\": \"mtcden\"}" -X POST $(report_url)
      az acr build -r $(acr_name) -t $(image_name) -f ./src/Dockerfile.MoleCloud --build-arg "pod_color=$(pod_color)" ./src
      
      # Package the helm chart and push it to ACR
      curl -d "{\"State\": 2, \"Message\": \"Initializing Helm...\", \"ServiceName\": \"mtcden\"}" -X POST $(report_url)
      helm init --client-only

      curl -d "{\"State\": 2, \"Message\": \"Packaging Helm Chart...\", \"ServiceName\": \"mtcden\"}" -X POST $(report_url)
      helm package charts/mole-cloud --version $(Build.BuildNumber)

      curl -d "{\"State\": 2, \"Message\": \"Pushing Helm chart to Azure Container Registry...\", \"ServiceName\": \"mtcden\"}" -X POST $(report_url)
      az acr helm push -n $(acr_name) mole-cloud-$(Build.BuildNumber).tgz

- script: |
    curl -d "{\"State\": 5, \"Message\": \"Error Building Application\", \"ServiceName\": \"mtcden\"}" -X POST $(report_url)
  condition: failed()
