pool:
  vmImage: 'ubuntu-16.04'

trigger:
  branches: 
    include:
      - master
  paths:
    include:
      - src/WhackAMole.KubeAdmin
      - src/WhackAMole.KubeServices

variables:
  acr_name: mtcdensandboxdemo
  registry: $(mtcdensandboxdemo).azurecr.io
  container_image_name: $(registry)/$(Build.Repository.Name)/kube-admin:$(Build.BuildId)


steps:
- task: AzureCLI@1
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: 'MTC Denver Sandbox (b0e04a4a-a321-4b66-b8fd-13715262ba3c)'
    scriptLocation: inlineScript
    inlineScript: |
      cd src/WhackAMole.KubeAdmin
      dotnet publish WhackAMole.KubeAdmin.csproj -c Release -o "./obj/Docker/Publish"

      az acr login --name $(acr_name)

      docker build . -t $(container_image_name)
      docker tag $(container_image_name) latest
      docker push $(container_image_name)
      docker push latest

      cp ../../charts/kube-admin $(build.artifactstagingdirectory)/helm/kube-admin -R

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

