name: $(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'ubuntu-16.04'

trigger:
  branches: 
    include:
      - master
  paths:
    include:
      - src/WhackAMole.KubeAdmin
      - src/WhackAMole.KubeServices

variables:
  acr_name: mtcdensandboxdemo
  registry: $(acr_name).azurecr.io
  image_name: $(registry)/$(Build.Repository.Name)/kube-admin:$(Build.BuildNumber)


steps:
- task: AzureCLI@1
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: 'MTC Denver Sandbox (b0e04a4a-a321-4b66-b8fd-13715262ba3c)'
    scriptLocation: inlineScript
    inlineScript: |
      cd src/WhackAMole.KubeAdmin
      dotnet publish WhackAMole.KubeAdmin.csproj -c Release -o "./obj/Docker/Publish"
      az acr-build --registry $(acr_name) --image $(image_name)

      cd ../../

      helm package .charts/kube-admin --version $(Build.BuildNumber)
      az acr helm push -n $(acr_name) kube-admin-$(Build.BuildNumber).tgz

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

